version: '3'
services:
  nest:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    working_dir: /opt/app
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ../:/opt/app
    depends_on:
      - db
  db:
    image: postgres:16.3-bullseye
    # If you want to persist DB information, add the following:
    # volumes:
    #   - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_volume:
