name: reviewdog
on:
  pull_request:
    branches: [main]
jobs:
  prettier:
    name: runner / prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Clean install
        run: pnpm install --frozen-lockfile
      - name: check-src
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          prettier_flags: 'src/**'
          fail_on_error: true
      - name: check-test
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          prettier_flags: 'test/**'
          fail_on_error: true
  on-success:
    name: runner / auto-merge
    runs-on: ubuntu-latest
    needs: [prettier, textlint]
    steps:
      - uses: actions/checkout@v4
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
